version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: english_bot
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-vocabmaster}
      POSTGRES_HOST: db
      REDIS_HOST: redis
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U english_bot -d vocabmaster"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: 
      - redis-server
      - --save 60 1
      - --loglevel warning
      - --maxmemory 256mb
      - --maxmemory-policy allkeys-lru

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: postgresql+asyncpg://english_bot:${POSTGRES_PASSWORD}@db:5432/vocabmaster
      REDIS_URL: redis://redis:6379/0
      BOT_NAME: vocabmaster_bot
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    ports:
      - "8000:8000"

volumes:
  db_data:
  redis_data: